src/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Merchandise__c</fullName>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDeleteRestrictInvoice.cls
@isTest
private class TestDeleteRestrictInvoice {
    // Invoice generator, with or without a Line Item
    static Invoice__c createNewInvoice(Boolean withLineItem) {
        // Create test Merchandise
            Merchandise__c merchandise = new Merchandise__c(
            Name = 'Test Laptop',
            Quantity__c = 1000,
            Price__c = 500);
        
        insert merchandise;
        
        // Create test Invoice 
        Invoice__c invoice = new Invoice__c();
        insert invoice;
        // Create test Line Item and insert it into the database, if withLineItem == true
        if (withLineItem) {
            Line_Item__c item = new Line_Item__c(
                name = '1',
            Quantity__c = 1,
            Merchandise__c = merchandise.Id,
            Invoice__c = invoice.Id
            );
            insert item;
    	}
    	return invoice;
	}
    
    // Single row Invoice with no Line Items => delete
    static testMethod void verifyInvoiceNoLineItemsDelete(){
        // Create test Invoice and insert it
        Invoice__c invoice = createNewInvoice(false);
        // Delete the Invoice, capture the result
        Database.DeleteResult result = Database.delete(invoice, false);
        // Assert success, because target Invoice doesn't have Line Items
        System.assert(result.isSuccess());
    }
}